global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "ml_app"
    scrape_interval: 5s
    static_configs:
      - targets: ["ml_app:5000"]
